[env]
CACHE_CONTROL = "max-age=0"

[[routes]]
method = "GET"
path = "/"
handler = "main"
[[routes.deploy]]
memory = 128

[plugins]
[plugins.deno]
module = "https://deno.land/x/deploy/deployctl.ts"
CacheLocation = "/tmp/deploy-cache"
