# fly.toml file generated for mirai-chat on 2023-04-12T00:53:04+03:00

app = "mirai-chat"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "ams"

[processes]
  app = "run --allow-all --unstable ./server.ts"

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
